name: Build and publish packages

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.200
    - name: Build
      run: dotnet build ./Xamarin.Forms.NeoControls/Xamarin.Forms.NeoControls.csproj --configuration Release
    - name: Pack
      run: dotnet pack ./Xamarin.Forms.NeoControls/Xamarin.Forms.NeoControls.csproj  --output ./artifacts --configuration Release
    - name: Push Nupkg to GitHub Packages
      uses: tanaka-takayoshi/nuget-publish-to-github-packages-action@v2.1
      with:
        nupkg-path:  './artifacts/*.nupkg'
        repo-owner:  'felipebaltazar'
        gh-user:  'felipebaltazar'
        token:  ${{ secrets.GITHUB_TOKEN }}